### ISSUE TITLE
Retrying skipped events of a dead letter queue in a safe manner

### ISSUE THREAD

**Issue by anschnapp** [flyeralarm/kafka-merge-purge#1]
For me it looks like it's not possible to retry skipped events of a dlq without also be "re asked" about the already merged and purged events (only if log compaction has not cleaned it up in the meantime).

When I first run the CLI tool, let's say for a dead letter queue "event-dlq", a retry topic "event-retry" and a given group id "dlq-handling-group".

I could decide for each event if i want to skip, merge or purge.

AFAIK skipping do nothing (but in commit mode it's commit the offset), merging put it to a given retry queue and purging creates a tombstone event...

Let's imagine i skipped message `#1`, merged `#2` and purged `#3`.

Now some new messages appear: `#4` and `#5`

Let's say i want now to process all not handled events of the "event-dlq" topic.

If I use same group id asking would start only with new messages, so it would start for message #4.

If I use a different group id, the tool will ask me for all messages which includes the merged and depending on log compaction maybe also the purged ones.

So, I don't see a way to reprocess a dlq topic in a way where i would:
* re asked for skipped events
* leaving out the purged events in a safe way (i think depending on log compaction is quite error prone)
* being asked about new events

**Comment by domnikl** [comment]
Hi @anschnapp,
first of all, thanks for the issue! I went through your scenario and I am not sure how you'd use kafka-merge-purge. First of all you should use a different DLQ for every service that consumes events, as they might fail consumption for different messages. Therefor you need to use the same group id when running kafka-merge-purge for the same DLQ but use different DLQs for different consumer (group)s.

Skipped events will need no reprocessing, so you won't be asked for it, they will just be ignored. If you don't use log compaction, you can just skip events instead of purging them as the result is the same - they will be ignored and no longer come up for reprocessing in your application.

If you merge events, it's then your applications duty to reprocess them and decide whether they should be written to the DLQ again and if they do, they will come up in kafka-merge-purge as new events and you will be asked again for it.

---

Here's your scenario in detail:

- `#1` skipped -> nothing happens except committing offset
- `#2` merged -> will be reprocessed by the application as a new message, fails again, application writes to `event-dlq` again
- `#3` purged -> tombstone record
- `#4`
- `#5`
- `#2` will be asked again

Does that answer your question?
